services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: transacoes-simplificadas.app
        expose:
            - "9000"
        volumes:
            - .:/var/www/app:delegated
            - ./storage/logs:/var/www/app/storage/logs
        networks:
            - transacoes-simplificadas.network
        extra_hosts:
            - host.docker.internal:host-gateway

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: transacoes-simplificadas.worker
        command: php artisan listener:send-credit-notification
        volumes:
            - .:/var/www/app:delegated
            - ./storage/logs:/var/www/app/storage/logs
        networks:
            - transacoes-simplificadas.network

    nginx:
        image: nginx:alpine
        container_name: transacoes-simplificadas.webserver
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/app:delegated
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - transacoes-simplificadas.network

    db:
        container_name: transacoes-simplificadas.db
        image: postgres:16
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - ./docker/database/.env
        networks:
            - transacoes-simplificadas.network

    redis:
        container_name: transacoes-simplificadas.cache
        image: redis
        command: redis-server
        ports:
            - "6379:6379"
        networks:
            - transacoes-simplificadas.network

    zookeeper:
        container_name: transacoes-simplificadas.zookeeper
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - transacoes-simplificadas.network

    kafka:
        container_name: transacoes-simplificadas.kafka
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://transacoes-simplificadas.kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - transacoes-simplificadas.network

    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        depends_on:
            - kafka
        ports:
            - 19000:9000
        environment:
            KAFKA_BROKERCONNECT: kafka:29092
        networks:
            - transacoes-simplificadas.network

networks:
    transacoes-simplificadas.network:

volumes:
    postgres-data:
        external: false
